#  SPDX-License-Identifier: BSD-3-Clause
#
#  pcre Makefile.uk
#
#  Authors: Costin Lupu <costin.lupu@cs.pub.ro>
#           Marc Rittinghaus <marc.rittinghaus@kit.edu>
#
#  Copyright (c) 2019, University Politehnica of Bucharest. All rights reserved.
#  Copyright (c) 2021, Karlsruhe Institute of Technology (KIT).
#                      All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from
#     this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

################################################################################
# Library registration
################################################################################
$(eval $(call addlib_s,libpcre,$(CONFIG_LIBPCRE)))

################################################################################
# Original sources
################################################################################
LIBPCRE_VERSION=8.45
LIBPCRE_BASENAME=pcre-$(LIBPCRE_VERSION)
LIBPCRE_URL=https://ftp.pcre.org/pub/pcre/pcre-$(LIBPCRE_VERSION).tar.gz
LIBPCRE_PATCHDIR=$(LIBPCRE_BASE)/patches
$(eval $(call fetch,libpcre,$(LIBPCRE_URL)))
$(eval $(call patch,libpcre,$(LIBPCRE_PATCHDIR),$(LIBPCRE_BASENAME)))

################################################################################
# Helpers
################################################################################
LIBPCRE_SRC = $(LIBPCRE_ORIGIN)/$(LIBPCRE_BASENAME)

################################################################################
# Library includes
################################################################################
CINCLUDES-$(CONFIG_LIBPCRE) += -I$(LIBPCRE_BASE)/include
LIBPCRE_CINCLUDES += -I$(LIBPCRE_BASE)/

CINCLUDES-$(CONFIG_LIBPCRE) += -I$(LIBPCRE_SRC)

################################################################################
# Global flags
################################################################################
LIBPCRE_FLAGS += -DHAVE_CONFIG_H
LIBPCRE_FLAGS += -U__SSE2__
LIBPCRE_FLAGS += -fcf-protection=none

# Suppress some warnings to make the build process look neater
LIBPCRE_FLAGS_SUPPRESS += -Wno-unused-parameter
LIBPCRE_FLAGS_SUPPRESS += -Wno-unused-variable
LIBPCRE_FLAGS_SUPPRESS += -Wno-unused-value
LIBPCRE_FLAGS_SUPPRESS += -Wno-unused-function
LIBPCRE_FLAGS_SUPPRESS += -Wno-unused-but-set-variable
LIBPCRE_FLAGS_SUPPRESS += -Wno-missing-field-initializers
LIBPCRE_FLAGS_SUPPRESS += -Wno-implicit-fallthrough
LIBPCRE_FLAGS_SUPPRESS += -Wno-int-to-pointer-cast
LIBPCRE_FLAGS_SUPPRESS += -Wno-pointer-to-int-cast

LIBPCRE_CFLAGS-y += $(LIBPCRE_FLAGS)
LIBPCRE_CFLAGS-y += $(LIBPCRE_FLAGS_SUPPRESS)

################################################################################
# Sources
################################################################################
LIBPCRE_SRCS += $(LIBPCRE_BASE)/pcre_chartables.c

################################################################################
# Library sources
################################################################################
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_byte_order.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_compile.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_config.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_dfa_exec.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_exec.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_fullinfo.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_get.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_globals.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_jit_compile.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_maketables.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_newline.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_ord2utf8.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_refcount.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_string_utils.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_study.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_tables.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_ucd.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_valid_utf8.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_version.c
LIBPCRE_SRCS += $(LIBPCRE_SRC)/pcre_xclass.c
